app = "n8npamec"

[env]
  DB_POSTGRESDB_PORT = "5432"
  DB_POSTGRESDB_USER = "postgres"
  DB_TYPE = "postgresdb"
  GENERIC_TIMEZONE = "Europe/Paris" # Change the Timezone here and on the next line
  TZ = "Europe/Paris"
  N8N_BASIC_AUTH_ACTIVE = "false"
  N8N_LOG_LEVEL= "info"
  N8N_DIAGNOSTICS_ENABLED = "false"
  N8N_ENCRYPTION_KEY = "SomeRandomAndSecureEncryptionKeyOfYourChoice"
  N8N_HIRING_BANNER_ENABLED = "false"
  N8N_USER_MANAGEMENT_DISABLED = "false"
  TINI_SUBREAPER = "true"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
